---
# playbook that exercises a serial patch and reboot of all the specified hosts
- name: patch and reboot
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Update package cache
      package:
        name: "*"
        state: latest
        update_cache: yes
      changed_when: false

    - name: Upgrade all packages
      package:
        name: "*"
        state: latest
      changed_when: true

    - name: reboot host
      ansible.builtin.reboot:
